### ISSUE TITLE
无意冒犯，但这个功能已经有完善的轮子了

### ISSUE THREAD

**Issue by TianyiShi2001** [stevenjoezhang/mmp-build#8]
如题。[pandoc](https://pandoc.org)就可以实现您所描述的功能，图片表格的cross-references，citation还有穿插tex命令都有很好的支持。所以，如果您想要pandoc中没有的一些特性，也许并不要重写全部逻辑，只需要做一些预处理再把剩下的扔给pandoc即可。

我平时就是用markdown（其实是[RMarkdown](http://rmarkdown.rstudio.com)）写作业然后通过pandoc排版成html和pdf的。这是一个例子：
- [markdown（其实是Rmd）](https://github.com/TianyiShi2001/ox/blob/master/content/tutorial/2020-03-03-how-has-ras-signalling-been-studied-in-c-elegans.Rmd)
- [PDF（LaTeX）](https://tianyishi2001.github.io/ox/tutorial/2020-03-03-how-has-ras-signalling-been-studied-in-c-elegans.pdf)
- [HTML](https://tianyishi2001.github.io/ox/tutorial/how-has-ras-signalling-been-studied-in-c-elegans.html)

RMarkdown对于pandoc的改进其实主要就是能把code block运行的结果计算并呈现出来。我倒是挺有兴趣把这个用typescript重写出来。上个月我初步地试着写一个能在node中简单地运行任何语言并返回结果的package：https://github.com/TianyiShi2001/panlang 。

**Comment by stevenjoezhang** [comment]
我此前试过了 pandoc 和 LaTeX 的 markdown 宏包，效果都不算满意，才决定造轮子。也许确实不需要重写全部逻辑，但我不太会 Haskell，所以无法优美地处理这个问题。最后干脆就写了个自己用着顺手的，不少内容都借鉴自 pandoc。

您的项目很有意思，我会关注一下。
